# Test oneOf
def testOneOf():
    assert oneOf(2, [1, 2, 3]) == Or(False, True, False)
    assert oneOf(4, [1, 2, 3]) == Or(False, False, False)
    assert oneOf(4, [4, 4, 4]) == Or(True, True, True)
    assert not oneOf(4, [1, 2, 3]) == Or(False, False, True)

# Test removeIfPresent
def testRemoveIfPresent():
    assert removeIfPresent(1, [1,2,3,4,5]) == [2, 3, 4, 5]
    assert removeIfPresent(7, [1,2,3,4,5]) == [1, 2, 3, 4, 5]
    assert not removeIfPresent(1, [1,2,3,4,5]) == []

# Test binOp
def testBinOp():
    a, b = Reals('a b')
    assert binOp(21, 4, '*', 3) == Or(And(True, a*b == 21),
                                      And(False, a/b == 21),
                                      And(False, a - b == 21),
                                      And(False, a + b == 21))
    
    assert binOp(46, 5, '/',3) == Or(And(False, a*b == 46),
                                     And(True, a/b == 46),
                                     And(False, a - b == 46),
                                     And(False, a + b == 46))
    
    assert binOp(6, 1, '+', 2) == Or(And(False, a*b == 6),
                                     And(False, a/b == 6),
                                     And(False, a - b == 6),
                                     And(True, a + b == 6))
    
    assert not binOp(36, 2, '-',3) == Or(And(False, a*b == 36),
                                         And(False, a/b == 36),
                                         And(True, a - b == 36),
                                         And(True, a + b == 36))

# Test triOp
def testTriOp():
    a, b, c = Reals('a b c')
    assert triOp(21, 1, '+', 4, '*', 5) == Or(And(True,
                                                  Or(And(False, a*b == 21/5),
                                                     And(False, a/b == 21/5),
                                                     And(False, a - b == 21/5),
                                                     And(True, a + b == 21/5))),
                                              And(False,
                                                  Or(And(False, a*b == 105),
                                                     And(False, a/b == 105),
                                                     And(False, a - b == 105),
                                                     And(True, a + b == 105))),
                                              And(False,
                                                  Or(And(False, a*b == 26),
                                                     And(False, a/b == 26),
                                                     And(False, a - b == 26),
                                                     And(True, a + b == 26))),
                                              And(False,
                                                  Or(And(False, a*b == 16),
                                                     And(False, a/b == 16),
                                                     And(False, a - b == 16),
                                                     And(True, a + b == 16))))
    assert triOp(25, 2, '-', 4, '/', 6) == Or(And(False,
                                                  Or(And(False,
                                                         a*b == 4166666666666667/1000000000000000),
                                                     And(False,
                                                         a/b == 4166666666666667/1000000000000000),
                                                     And(True,
                                                         a - b == 4166666666666667/1000000000000000),
                                                     And(False,
                                                         a + b == 4166666666666667/1000000000000000))),
                                              And(True,
                                                  Or(And(False, a*b == 150),
                                                     And(False, a/b == 150),
                                                     And(True, a - b == 150),
                                                     And(False, a + b == 150))),
                                                  And(False,
                                                      Or(And(False, a*b == 31),
                                                         And(False, a/b == 31),
                                                         And(True, a - b == 31),
                                                         And(False, a + b == 31))),
                                                  And(False,
                                                      Or(And(False, a*b == 19),
                                                         And(False, a/b == 19),
                                                         And(True, a - b == 19),
                                                         And(False, a + b == 19))))

    assert triOp(55, 21, '-', 4, '+', 11) == Or(And(False,
                                                        Or(And(False, a*b == 5),
                                                           And(False, a/b == 5),
                                                           And(True, a - b == 5),
                                                           And(False, a + b == 5))),
                                                    And(False,
                                                        Or(And(False, a*b == 605),
                                                           And(False, a/b == 605),
                                                           And(True, a - b == 605),
                                                           And(False, a + b == 605))),
                                                    And(False,
                                                        Or(And(False, a*b == 66),
                                                           And(False, a/b == 66),
                                                           And(True, a - b == 66),
                                                           And(False, a + b == 66))),
                                                    And(True,
                                                        Or(And(False, a*b == 44),
                                                           And(False, a/b == 44),
                                                           And(True, a - b == 44),
                                                           And(False, a + b == 44))))

    assert not triOp(31, 17, '/', 9, '*', 5) == Or(And(False,
                                                           Or(And(False, a*b == 31/5),
                                                              And(True, a/b == 31/5),
                                                              And(False, a - b == 31/5),
                                                              And(False, a + b == 31/5))),
                                                       And(False,
                                                           Or(And(False, a*b == 155),
                                                              And(True, a/b == 155),
                                                              And(False, a - b == 155),
                                                              And(False, a + b == 155))),
                                                       And(False,
                                                           Or(And(False, a*b == 36),
                                                              And(True, a/b == 36),
                                                              And(False, a - b == 36),
                                                              And(False, a + b == 36))),
                                                       And(False,
                                                           Or(And(False, a*b == 26),
                                                              And(True, a/b == 26),
                                                              And(False, a - b == 26),
                                                              And(False, a + b == 26))))

# Test quadOp
def testQuadOp():
    a, b, c = Reals('a b c')
    o3 = Strings('o3')
    assert quadOp(21, 1, '+', 2, '-', 4, '/', 6) == Or(And(False,
                                                           Or(And(False,
                                                                  Or(And(False, a*b == 7/8),
                                                                     And(False, a/b == 7/8),
                                                                     And(False, a - b == 7/8),
                                                                     And(True, a + b == 7/8))),
                                                              And(False,
                                                                  Or(And(False, a*b == 14),
                                                                     And(False, a/b == 14),
                                                                     And(False, a - b == 14),
                                                                     And(True, a + b == 14))),
                                                              And(True,
                                                                  Or(And(False, a*b == 15/2),
                                                                     And(False, a/b == 15/2),
                                                                     And(False, a - b == 15/2),
                                                                     And(True, a + b == 15/2))),
                                                              And(False,
                                                                  Or(And(False, a*b == -1/2),
                                                                     And(False, a/b == -1/2),
                                                                     And(False, a - b == -1/2),
                                                                     And(True, a + b == -1/2))))),
                                                       And(True,
                                                           Or(And(False,
                                                                  Or(And(False, a*b == 63/2),
                                                                     And(False, a/b == 63/2),
                                                                     And(False, a - b == 63/2),
                                                                     And(True, a + b == 63/2))),
                                                              And(False,
                                                                  Or(And(False, a*b == 504),
                                                                     And(False, a/b == 504),
                                                                     And(False, a - b == 504),
                                                                     And(True, a + b == 504))),
                                                              And(True,
                                                                  Or(And(False, a*b == 130),
                                                                     And(False, a/b == 130),
                                                                     And(False, a - b == 130),
                                                                     And(True, a + b == 130))),
                                                              And(False,
                                                                  Or(And(False, a*b == 122),
                                                                     And(False, a/b == 122),
                                                                     And(False, a - b == 122),
                                                                     And(True, a + b == 122))))),
                                                       And(False,
                                                           Or(And(False,
                                                                  Or(And(False, a*b == 27/4),
                                                                     And(False, a/b == 27/4),
                                                                     And(False, a - b == 27/4),
                                                                     And(True, a + b == 27/4))),
                                                              And(False,
                                                                  Or(And(False, a*b == 108),
                                                                     And(False, a/b == 108),
                                                                     And(False, a - b == 108),
                                                                     And(True, a + b == 108))),
                                                              And(True,
                                                                  Or(And(False, a*b == 31),
                                                                     And(False, a/b == 31),
                                                                     And(False, a - b == 31),
                                                                     And(True, a + b == 31))),
                                                              And(False,
                                                                  Or(And(False, a*b == 23),
                                                                     And(False, a/b == 23),
                                                                     And(False, a - b == 23),
                                                                     And(True, a + b == 23))))),
                                                       And(False,
                                                           Or(And(False,
                                                                  Or(And(False, a*b == 15/4),
                                                                     And(False, a/b == 15/4),
                                                                     And(False, a - b == 15/4),
                                                                     And(True, a + b == 15/4))),
                                                              And(False,
                                                                  Or(And(False, a*b == 60),
                                                                     And(False, a/b == 60),
                                                                     And(False, a - b == 60),
                                                                     And(True, a + b == 60))),
                                                              And(True,
                                                                  Or(And(False, a*b == 19),
                                                                     And(False, a/b == 19),
                                                                     And(False, a - b == 19),
                                                                     And(True, a + b == 19))),
                                                              And(False,
                                                                  Or(And(False, a*b == 11),
                                                                     And(False, a/b == 11),
                                                                     And(False, a - b == 11),
                                                                     And(True, a + b == 11))))))

    assert quadOp(31, 2, '*', 7, '/', 4, '/', 11) ==  Or(And(False,
                                                             Or(And(False,
                                                                    Or(And(True,
                                                                           a*b == 3522727272727273/5000000000000000),
                                                                       And(False,
                                                                           a/b == 3522727272727273/5000000000000000),
                                                                       And(False,
                                                                           a - b == 3522727272727273/5000000000000000),
                                                                       And(False,
                                                                           a + b == 3522727272727273/5000000000000000))),
                                                                And(True,
                                                                    Or(And(True,
                                                                           a*b == 11272727272727273/1000000000000000),
                                                                       And(False,
                                                                           a/b == 11272727272727273/1000000000000000),
                                                                       And(False,
                                                                           a - b == 11272727272727273/1000000000000000),
                                                                       And(False,
                                                                           a + b == 11272727272727273/1000000000000000))),
                                                                And(False,
                                                                    Or(And(True,
                                                                           a*b == 3409090909090909/500000000000000),
                                                                       And(False,
                                                                           a/b == 3409090909090909/500000000000000),
                                                                       And(False,
                                                                           a - b == 3409090909090909/500000000000000),
                                                                       And(False,
                                                                           a + b == 3409090909090909/500000000000000))),
                                                                And(False,
                                                                    Or(And(True,
                                                                           a*b == -11818181818181817/10000000000000000),
                                                                       And(False,
                                                                           a/b == -11818181818181817/10000000000000000),
                                                                       And(False,
                                                                           a - b == -11818181818181817/10000000000000000),
                                                                       And(False,
                                                                           a + b == -11818181818181817/10000000000000000))))),
                                                         And(True,
                                                             Or(And(False,
                                                                    Or(And(True, a*b == 341/4),
                                                                       And(False, a/b == 341/4),
                                                                       And(False, a - b == 341/4),
                                                                       And(False, a + b == 341/4))),
                                                                And(True,
                                                                    Or(And(True, a*b == 1364),
                                                                       And(False, a/b == 1364),
                                                                       And(False, a - b == 1364),
                                                                       And(False, a + b == 1364))),
                                                                And(False,
                                                                    Or(And(True, a*b == 345),
                                                                       And(False, a/b == 345),
                                                                       And(False, a - b == 345),
                                                                       And(False, a + b == 345))),
                                                                And(False,
                                                                    Or(And(True, a*b == 337),
                                                                       And(False, a/b == 337),
                                                                       And(False, a - b == 337),
                                                                       And(False, a + b == 337))))),
                                                         And(False,
                                                             Or(And(False,
                                                                    Or(And(True, a*b == 21/2),
                                                                       And(False, a/b == 21/2),
                                                                       And(False, a - b == 21/2),
                                                                       And(False, a + b == 21/2))),
                                                                And(True,
                                                                    Or(And(True, a*b == 168),
                                                                       And(False, a/b == 168),
                                                                       And(False, a - b == 168),
                                                                       And(False, a + b == 168))),
                                                                And(False,
                                                                    Or(And(True, a*b == 46),
                                                                       And(False, a/b == 46),
                                                                       And(False, a - b == 46),
                                                                       And(False, a + b == 46))),
                                                                And(False,
                                                                    Or(And(True, a*b == 38),
                                                                       And(False, a/b == 38),
                                                                       And(False, a - b == 38),
                                                                       And(False, a + b == 38))))),
                                                         And(False,
                                                             Or(And(False,
                                                                    Or(And(True, a*b == 5),
                                                                       And(False, a/b == 5),
                                                                       And(False, a - b == 5),
                                                                       And(False, a + b == 5))),
                                                                And(True,
                                                                    Or(And(True, a*b == 80),
                                                                       And(False, a/b == 80),
                                                                       And(False, a - b == 80),
                                                                       And(False, a + b == 80))),
                                                                And(False,
                                                                    Or(And(True, a*b == 24),
                                                                       And(False, a/b == 24),
                                                                       And(False, a - b == 24),
                                                                       And(False, a + b == 24))),
                                                                And(False,
                                                                    Or(And(True, a*b == 16),
                                                                       And(False, a/b == 16),
                                                                       And(False, a - b == 16),
                                                                       And(False, a + b == 16))))))

    assert not quadOp(41, 12, '*', 5, '-', 4, '/', 2) == Or(And(False,
                                                                Or(And(False,
                                                                       Or(And(False, a*b == 41/8),
                                                                          And(False, a/b == 41/8),
                                                                          And(False, a - b == 41/8),
                                                                          And(False, a + b == 41/8))),
                                                                   And(False,
                                                                       Or(And(True, a*b == 82),
                                                                          And(False, a/b == 82),
                                                                          And(False, a - b == 82),
                                                                          And(False, a + b == 82))),
                                                                   And(True,
                                                                       Or(And(True, a*b == 49/2),
                                                                          And(False, a/b == 49/2),
                                                                          And(False, a - b == 49/2),
                                                                          And(False, a + b == 49/2))),
                                                                   And(False,
                                                                       Or(And(True, a*b == 33/2),
                                                                          And(False, a/b == 33/2),
                                                                          And(False, a - b == 33/2),
                                                                          And(False, a + b == 33/2))))),
                                                            And(True,
                                                                Or(And(False,
                                                                       Or(And(True, a*b == 41/2),
                                                                          And(False, a/b == 41/2),
                                                                          And(False, a - b == 41/2),
                                                                          And(False, a + b == 41/2))),
                                                                   And(False,
                                                                       Or(And(True, a*b == 328),
                                                                          And(False, a/b == 328),
                                                                          And(False, a - b == 328),
                                                                          And(False, a + b == 328))),
                                                                   And(True,
                                                                       Or(And(True, a*b == 86),
                                                                          And(False, a/b == 86),
                                                                          And(False, a - b == 86),
                                                                          And(False, a + b == 86))),
                                                                   And(False,
                                                                       Or(And(True, a*b == 78),
                                                                          And(False, a/b == 78),
                                                                          And(False, a - b == 78),
                                                                          And(False, a + b == 78))))),
                                                            And(False,
                                                                Or(And(False,
                                                                       Or(And(True, a*b == 43/4),
                                                                          And(False, a/b == 43/4),
                                                                          And(False, a - b == 43/4),
                                                                          And(False, a + b == 43/4))),
                                                                   And(False,
                                                                       Or(And(True, a*b == 172),
                                                                          And(False, a/b == 172),
                                                                          And(False, a - b == 172),
                                                                          And(False, a + b == 172))),
                                                                   And(True,
                                                                       Or(And(True, a*b == 47),
                                                                          And(False, a/b == 47),
                                                                          And(False, a - b == 47),
                                                                          And(False, a + b == 47))),
                                                                   And(False,
                                                                       Or(And(True, a*b == 39),
                                                                          And(False, a/b == 39),
                                                                          And(False, a - b == 39),
                                                                          And(False, a + b == 39))))),
                                                            And(False,
                                                                Or(And(False,
                                                                       Or(And(True, a*b == 39/4),
                                                                          And(False, a/b == 39/4),
                                                                          And(False, a - b == 39/4),
                                                                          And(False, a + b == 39/4))),
                                                                   And(False,
                                                                       Or(And(True, a*b == 156),
                                                                          And(False, a/b == 156),
                                                                          And(False, a - b == 156),
                                                                          And(False, a + b == 156))),
                                                                   And(True,
                                                                       Or(And(True, a*b == 43),
                                                                          And(False, a/b == 43),
                                                                          And(False, a - b == 43),
                                                                          And(False, a + b == 43))),
                                                                   And(False,
                                                                       Or(And(True, a*b == 35),
                                                                          And(False, a/b == 35),
                                                                          And(False, a - b == 35),
                                                                          And(False, a + b == 35))))))

# Test pentaOp
def testPentaOp():
    a, b, c, d = Reals('a b c d')
    
    assert not pentaOp(31, 1, '*', 12, '-', 3, '*', 6, '+', 4) == Or(And(False,
                                                                     Or(And(False,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(True,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 70),
                                                                                      And(False, a/b == 70),
                                                                                      And(False, a - b == 70),
                                                                                      And(True, a + b == 70))))),
                                                                        And(False,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(True,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 70),
                                                                                      And(False, a/b == 70),
                                                                                      And(False, a - b == 70),
                                                                                      And(True, a + b == 70))))),
                                                                        And(False,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(True,
                                                                                   Or(And(False, a*b == 73),
                                                                                      And(False, a/b == 73),
                                                                                      And(False, a - b == 73),
                                                                                      And(True, a + b == 73))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))))),
                                                                        And(True,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 70),
                                                                                      And(False, a/b == 70),
                                                                                      And(False, a - b == 70),
                                                                                      And(True, a + b == 70))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 70),
                                                                                      And(False, a/b == 70),
                                                                                      And(False, a - b == 70),
                                                                                      And(True, a + b == 70))),
                                                                               And(True,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 69),
                                                                                      And(False, a/b == 69),
                                                                                      And(False, a - b == 69),
                                                                                      And(True, a + b == 69))))))),
                                                                 And(False,
                                                                     Or(And(False,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(True,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 70),
                                                                                      And(False, a/b == 70),
                                                                                      And(False, a - b == 70),
                                                                                      And(True, a + b == 70))))),
                                                                        And(False,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(True,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 70),
                                                                                      And(False, a/b == 70),
                                                                                      And(False, a - b == 70),
                                                                                      And(True, a + b == 70))))),
                                                                        And(False,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(True,
                                                                                   Or(And(False, a*b == 73),
                                                                                      And(False, a/b == 73),
                                                                                      And(False, a - b == 73),
                                                                                      And(True, a + b == 73))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))))),
                                                                        And(True,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 70),
                                                                                      And(False, a/b == 70),
                                                                                      And(False, a - b == 70),
                                                                                      And(True, a + b == 70))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 70),
                                                                                      And(False, a/b == 70),
                                                                                      And(False, a - b == 70),
                                                                                      And(True, a + b == 70))),
                                                                               And(True,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 69),
                                                                                      And(False, a/b == 69),
                                                                                      And(False, a - b == 69),
                                                                                      And(True, a + b == 69))))))),
                                                                 And(False,
                                                                     Or(And(False,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(True,
                                                                                   Or(And(False, a*b == 73),
                                                                                      And(False, a/b == 73),
                                                                                      And(False, a - b == 73),
                                                                                      And(True, a + b == 73))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 71),
                                                                                      And(False, a/b == 71),
                                                                                      And(False, a - b == 71),
                                                                                      And(True, a + b == 71))))),
                                                                        And(False,
                                                                            Or(And(False,
                                                                                   Or(And(False, a*b == 72),
                                                                                      And(False, a/b == 72),
                                                                                      And(False, a - b == 72),
                                                                                      And(True, a + b == 72))),
                                                                               And(False,
                                                                                   Or(And(False, a*b == 72),
                                                                                   And(False, a/b == 72),
                                                                                   And(False, a - b == 72),
                                                                                   And(True, a + b == 72))))))))

# Test outDistinct  
def testOurDistinct():
    assert our_distinct(1,2,3,4,4,[1,2,3,4]) == And(True, True, True, True, False)
    assert our_distinct(1,2,3,4,5,[1,2,3,4,5]) == And(True, True, True, True, True)
    assert our_distinct(1,1,1,1,1,[1]) == And(True, False, False, False, False)

# Test findSolutions
def testFindSolutions():
    assert findSolutions(21,[1,2,3,4,5]) == None
    assert findSolutions(25,[1,2,3,6,5]) == None
    
# Will print "Everything passed" if none of the test fails
if __name__ == "__main__":
    testOneOf()
    testBinOp()
    testTriOp()
    testQuadOp()
    testPentaOp()
    testRemoveIfPresent()
    testOurDistinct()
    testFindSolutions()
    print("Everything passed")
